name: Daily Dependency Update

on: [push]

env:
  variable_de_entorno: "Esta es una variable de entorno papa"

jobs:
  update-dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Instalacion de node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Impresion
        run: echo "${{github.actor}}"
      - name: Impriomir variablr de entorno a nivel de wokflow
        run: echo "la variable es ${{env.variable_de_entorno}}"
      - name: Imprimiendo secret
        run: echo "${{ secrets.TOKEN_TB }}"
