name: adios mundo cruel
run-name: Cron jobs

on: [push]

jobs:
  Quiubole:
    runs-on: ubuntu-latest
    steps:
      - name: Clonado del repositorio lml
        uses: actions/checkout@v4
      - name: Instalacion de nodeJS lml
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Finalmente leemos el Archivo papirrin
        run: node src/script.js
