name: GitHub Action Learning

on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/15 * * * *"

env:
  variable_de_entorno: "Esta es una variable de entorno papa"

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Node Installation
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Printing
        run: echo "${{ github.actor }}"

      - name: Printing environment variable at workflow level
        run: echo "The variable is ${{ env.variable_de_entorno }}"

      - name: Printing secret
        run: echo "${{ secrets.TOKEN_TB }}"

      - name: Print moi_var
        run: echo "This is the variable to print... ${{ vars.MOI_VAR }}"

  commit-automatico:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repo
        uses: actions/checkout@v4

      - name: Git configuration
        run: |
          git config --global user.email "mc.moisesm16@gmail.com"
          git config --global user.name "Moises Baldenegro Melendez"

      - name: Get date and time
        id: get_date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d-%H:%M:%S')"

      - name: Creating LOG file
        run: touch src/logs/$(date +'%Y-%m-%d-%H:%M:%S').txt

      - name: Adding information to the file
        run: |
          echo "Created at: ${{ steps.get_date.outputs.date }}" > src/logs/$(date +'%Y-%m-%d-%H:%M:%S').txt

      - name: Committing changes
        run: |
          git add .
          git commit -m "Add new file automatically on ${{ steps.get_date.outputs.date }}"

      - name: Pushing changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TOKEN_TB }}
