name: GitHuhb Action Learning

on:
  push:
    branches:
      - main

  schedule:
    - cron: "*/15 * * * *"

env:
  variable_de_entorno: "Esta es una variable de entorno papa"

jobs:
  update-dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Instalacion de node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Impresion
        run: echo "${{github.actor}}"

      - name: Impriomir variablr de entorno a nivel de wokflow
        run: echo "la variable es ${{env.variable_de_entorno}}"

      - name: Imprimiendo secret
        run: echo "${{ secrets.TOKEN_TB }}"

      - name: Print moi_var
        run: echo "Esta es la variable a imprimir... ${{ vars.MOI_VAR}}"

  commit-automatico:
    runs-on: ubuntu-latest

    steps:
      - name: Clonamos el repo
        uses: actions/checkout@v4

      - name: Configuracion de git
        run: |
          git config --global user.email "mc.moisesm16@gmail.com"
          git config --global user.name "Moises Baldenegro Melendez"

      - name: Obtenemos la fecha
        id: get_date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Creacion del archivo de LOG
        run: touch src/$(date +'%Y-%m-%d').txt

      - name: Agregamos informacion al archivo
        run: |
          echo "Created at: ${{ steps.get_date.outputs.date }}" > src/$(date +'%Y-%m-%d').txt

      - name: Hacemos el commit
        run: |
          git add .
          git commit -m "Add new file automatically on ${{ steps.get_date.outputs.date }}"
      - name: Por ultimo pusheamos cambios
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TOKEN_TB }}
