name: Daily Dependency Update

on: [push]

jobs:
  update-dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Instalacion de node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Impresion
        run: " ${{github.actor}}"
